# executable files for this directory
OBJECTS = absInt.exe accum.exe accum4.exe \
		  avg_price.exe bind2.exe elimDups.exe equal.exe \
		  equiv-istream-iter.exe inserters.exe \
		  iostream_iter.exe newcount-size.exe \
		  ostreamIter2.exe rcomma.exe \
		  reverse.exe reverse-iter.exe rev-iters.exe \
		  sortSI.exe use_find.exe use-istream-iter.exe

# the corresponding source file uses c++ 11 features
C11_OBJECTS = lambda.exe 

# tells make to use the file "..\MS_makefile_template", which
# defines general rules for making .obj and .exe files
include ..\MS_makefile_template

LOCFLAGS = /I..\1 -I..\6

