DIRS = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19

all:  
	cd 1 && nmake 
	cd 2 && nmake 
	cd 3 && nmake 
	cd 4 && nmake 
	cd 5 && nmake 
	cd 6 && nmake
	cd 7 && nmake 
	cd 8 && nmake 
	cd 9 && nmake
	cd 10 && nmake
	cd 11 && nmake
	cd 12 && nmake
	cd 13 && nmake 
	cd 14 && nmake 
	cd 15 && nmake 
	cd 16 && nmake 
	cd 17 && nmake 
	cd 18 && nmake 
	cd 19 && nmake

clean: 
	cd 1 && nmake clean 
	cd 2 && nmake clean 
	cd 3 && nmake clean 
	cd 4 && nmake clean 
	cd 5 && nmake clean 
	cd 6 && nmake clean 
	cd 7 && nmake clean 
	cd 8 && nmake clean 
	cd 9 && nmake clean
	cd 10 && nmake clean
	cd 11 && nmake clean
	cd 12 && nmake clean
	cd 13 && nmake clean 
	cd 14 && nmake clean 
	cd 15 && nmake clean 
	cd 16 && nmake clean 
	cd 17 && nmake clean 
	cd 18 && nmake clean 
	cd 19 && nmake clean

clobber: 
	cd 1 && nmake clobber 
	cd 2 && nmake clobber 
	cd 3 && nmake clobber 
	cd 4 && nmake clobber 
	cd 5 && nmake clobber 
	cd 6 && nmake clobber 
	cd 7 && nmake clobber 
	cd 8 && nmake clobber 
	cd 9 && nmake clobber
	cd 10 && nmake clobber
	cd 11 && nmake clobber
	cd 12 && nmake clobber
	cd 13 && nmake clobber 
	cd 14 && nmake clobber 
	cd 15 && nmake clobber 
	cd 16 && nmake clobber 
	cd 17 && nmake clobber 
	cd 18 && nmake clobber 
	cd 19 && nmake clobber

