# executable files for this directory
OBJECTS = capacity.exe erase1.exe erase2.exe find_ops.exe \
		  find-str.exe refreshIter.exe stack.exe \
		  str_assignOps.exe substr.exe useConvs.exe

# tells make to use the file "..\MS_makefile_template", which
# defines general rules for making .obj and .exe files
include ..\MS_makefile_template

LOCFLAGS = /I..\7

