# executable files for this directory
OBJECTS = add_item2.exe doWhile.exe guess.exe ifgrades.exe \
		  othercnt.exe rangefor.exe vowels.exe 

# tells make to use the file "..\MS_makefile_template", which
# defines general rules for making .obj and .exe files
include ..\MS_makefile_template

LOCFLAGS = /I..\1

